---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: R1
  gather_facts: no
  become: yes
  become_method: enable

  tasks:
    - name: BACKUP THE CONFIG
      eos_config:
        backup: yes
      register: config_output

    - name: RENAME BACKUP
      copy:
        src: ""
        dest: "./backup/.config"
