---

- name: Playbook create Loopback

  hosts: "{{ routers_id}}"
  connection: local
  become: yes
  become_method: enable
 
  vars_prompt:

    - name: routers_id
      prompt: Veuillez rentrer le nom du routeur sur lequel vous voulez créer la loopback
      private: no

    - name: loopback_name
      prompt: Veuillez mettre l'ID que vous voulez donner a votre loopback
      private: no

    - name: ip_address
      prompt: Veuillez mettre l'adresse IP de votre loopback
      private: no

    - name: netmask
      prompt: Veuillez mettre le masque de votre loopback
      private: no

  tasks: 

  - name: Creation loopback
    ios_interface:
      name: loopback {{ loopback_name }}
      state: present

  - name: Ajouter adresse IP loopback
    ios_config:
      authorize: yes
      lines:
        - interface loopback {{ loopback_name }}
        - ip address {{ ip_address }} {{ netmask }}

  - name: Show interfaces brief
    ios_command:
      commands: show ip int brief
    register: show_int

  - debug: var=show_int.stdout_lines
